baseURL = 'https://abhyuday-fr.github.io/'
locale = 'en-us'
title = 'Abhyuday Pundir'
theme = 'hugo-macchiato'

[params]
  comments = true
  faviconPack = true

# Top Navigation Menu
[[menu.main]]
  name = "Essential Coding Principles"
  url = "/essential-coding-principles"
  weight = 1

[[menu.main]]
  name = "Low-Latency"
  url = "/low-latency/"
  weight = 2

[[menu.main]]
  name = "Multithreading"
  url = "/multithreading/"
  weight = 3

[[menu.main]]
  name = "Networking"
  url = "/networking/"
  weight = 4

[[menu.main]]
  name = "Memory Allocation"
  url = "/memory-allocation/"
  weight = 5

  [params.giscus]
  repo = "abhyuday-fr/abhyuday-fr.github.io"
  repoId = "R_kgDOTu5T_w"
  category = "General"
  categoryId = "DIC_kwDOTu5T_84DCvLA"
  mapping = "pathname"
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "en"
